const fs = require('fs');
let c = fs.readFileSync('countryPrompts.js', 'utf8');
const idx = c.indexOf('10. "barcode":');
if (idx > 0) {
    const before = c.substring(0, c.indexOf('9. "nationality": Translate nationality to English', idx) + 124);
    const appended = before + `10. "barcode": Numerical or alphanumeric code printed near the barcode.\\n11. "dateOfBirth": Date of birth formatted strictly as "DD Month YYYY" (e.g., "15 March 1988").\\n12. "placeOfBirth": Place of birth translated to English (e.g., "Paris, France").\\n13. "issueDate": Issue date formatted strictly as "DD Month YYYY".\\n14. "expiryDate": Expiration date formatted strictly as "DD Month YYYY".\\n15. "authority": Translate issuing authority to English AND append the country name at the end separated by a comma (e.g., "Police Prefecture, France" or "Ministry of Transport, Colombia").\\n16. "class": Extract driving categories list (e.g., "AM, A1, B, BE").\\n17. "categoriesDates": Extract category validity periods from the back table (e.g., "B: 10 Jan 2020 - 09 Jan 2035").\\n18. "codes": Restriction codes listed in column 12 (e.g., "01, 78").\\n19. "explicacionCodigos": Provide a professional English translation describing the allowed driving categories and any restriction codes (e.g., "Category B: Motor vehicles up to 3500kg... Code 01: Sight correction required").\\n\\nIf any field is missing or illegible, return an empty string (""). Return valid JSON.",
  "vietnam": "You are an expert OCR and document translation system specialized in Vietnamese driver's licenses.\\n\\nAnalyze the provided images of a driver's license.\\n\\nCRITICAL INSTRUCTION: ALL OUTPUT TEXT VALUES MUST BE TRANSLATED TO ENGLISH EXCEPT NAMES.\\nCRITICAL INSTRUCTION: For Vietnam, ONLY use the \`fullName\` field. DO NOT use \`surname\`, \`firstName\`, \`middleName\`, or \`firstNames\`. Set them to an empty string.\\n\\nEXTRACTION RULES:\\n1. \\"fullName\\": Extract the full name of the license holder exactly as it appears. Do not split into first, middle, and last names.\\n2. \\"surname\\": \\"\\"\\n3. \\"firstName\\": \\"\\"\\n4. \\"middleName\\": \\"\\"\\n5. \\"firstNames\\": \\"\\"\\n6. \\"licenseNumber\\": Primary document identification number (e.g., So/No.).\\n7. \\"dateOfBirth\\": Date of birth (Ngay sinh). Format strictly as \\"DD Month YYYY\\" (e.g., \\"15 March 1988\\").\\n8. \\"placeOfBirth\\": Place of birth. Translate location names to English.\\n9. \\"nationality\\": Nationality (Quoc tich). Translate to English (e.g., \\"Vietnamese\\").\\n10. \\"address\\": Residence address (Noi cu tru). Translate to English.\\n11. \\"issueDate\\": Issue date. Format strictly as \\"DD Month YYYY\\".\\n12. \\"expiryDate\\": Expiration date. Format strictly as \\"DD Month YYYY\\". If permanent, output \\"Indefinite\\".\\n13. \\"authority\\": Translate issuing authority to English AND append \\", Vietnam\\" at the end (e.g., \\"Department of Transport, Vietnam\\").\\n14. \\"class\\": Extract driving categories list (Hang/Class).\\n15. \\"categoriesDates\\": Extract category validity periods if available.\\n16. \\"codes\\": Restriction codes if any.\\n17. \\"explicacionCodigos\\": Provide a professional English translation describing the allowed driving categories and any restriction codes.\\n\\nIf any field is missing or illegible, return an empty string (\\"\\"). Return valid JSON matching the schema.",
  "indonesia": "You are an expert OCR and document translation system specialized in Indonesian driver's licenses (Surat Izin Mengemudi).\\n\\nAnalyze the provided images of a driver's license.\\n\\nCRITICAL INSTRUCTION: ALL OUTPUT TEXT VALUES MUST BE TRANSLATED TO ENGLISH EXCEPT NAMES.\\n\\nEXTRACTION RULES:\\n1. \\"surname\\": Extract the surname if distinct, otherwise leave empty or use the last word of the name.\\n2. \\"firstName\\": Extract the first name.\\n3. \\"middleName\\": Extract any middle names.\\n4. \\"firstNames\\": Extract all first and middle names.\\n5. \\"fullName\\": Extract the full name exactly as it appears (Field 1).\\n6. \\"dateOfBirth\\": Date of birth (Field 2, after comma). Format strictly as \\"DD Month YYYY\\" (e.g., \\"15 March 1988\\").\\n7. \\"placeOfBirth\\": Place of birth (Field 2, before comma). Translate location names to English if applicable.\\n8. \\"blood\\": Extract blood type from Field 3 (e.g., 'O').\\n9. \\"gender\\": Extract gender from Field 3 (e.g., 'PRIA' = 'Male', 'WANITA' = 'Female'). Output MUST be strictly 'Male' or 'Female'.\\n10. \\"address\\": Residence address (Field 4). Translate to English.\\n11. \\"issueDate\\": Issue date (bottom right, or based on expiry). Format strictly as \\"DD Month YYYY\\".\\n12. \\"expiryDate\\": Expiration date (bottom right). Format strictly as \\"DD Month YYYY\\".\\n13. \\"licenseNumber\\": Extract the license number (top right, under the class letter).\\n14. \\"authority\\": Translate issuing authority to English AND append \\", Indonesia\\" at the end.\\n15. \\"class\\": Extract driving category (Class letter, e.g., 'A', 'C').\\n16. \\"code\\": Extract the alphanumeric code found on the REVERSE (BACK) side of the license (e.g. 'L08659865').\\n17. \\"explicacionCodigos\\": Provide a professional English translation describing the allowed driving categories if possible.\\n\\nIf any field is missing or illegible, return an empty string (\\"\\"). Return valid JSON matching the schema."
};`;
    fs.writeFileSync('countryPrompts.js', appended);
    console.log("Fixed.");
}
